TVDailyCriticUI/ViewModels/MovieViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TVDailyCriticUI.ViewModels
{
    public class MovieViewModel
    {
        public int MovieId { get; set; }

        [Display(Name = "Created date")]
        [DataType(DataType.Date)]
        public DateTime CreatedDate { get; set; }

        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }

        [Display(Name = "Title")]
        public string MovieTitle { get; set; }

        public string Description { get; set; }
        public string Director { get; set; }
        public string Producer { get; set; }
        public string Writer { get; set; }

        public byte[] Image { get; set; }

        [NotMapped]
        public virtual ICollection<UserViewModel> Users { get; set; }
        [NotMapped]
        public virtual ICollection<CommentViewModel> Comments { get; set; }

        [NotMapped]
        public IFormFile ImageFile { get; set; }
        public int AddedBy { get; set; }
    }
}

TVDailyCriticUI/ViewModels/RatingsStatisticsViewModel.cs
namespace TVDailyCriticUI.ViewModels
{
    public class RatingsStatisticsViewModel
    {
        public int PercentageMenRating { get; set; }
        public int PercentageWomenRating { get; set; }
        public int PercentageAdultsRating { get; set; }
        public int PercentageTeenagersRating { get; set; }
        public int ModeRating { get; set; }
        public int MeanRating { get; set; }
        public string MovieTitle { get; set; }
        public int TotalUsers { get; set; }
    }
}

TVDailyCriticUI/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using TVDailyCriticUI.ViewModels;
using TVDailyCriticUI.Services;
using TVDailyCriticUI.AuthHandler;

namespace TVDailyCriticUI.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;
        private readonly SessionManager _sessionManager;

        public CommentController(ICommentService commentService, SessionManager sessionManager)
        {
            _commentService = commentService;
            _sessionManager = sessionManager;
        }

        public IActionResult Insert(CommentViewModel comment)
        {
            comment.UserId = _sessionManager.UserId;
            _commentService.Create(comment);
            return RedirectToAction("List", "Movie");
        }

        public IActionResult Create(int id)
        {
            var vm = new CommentViewModel
            {
                 UserId = _sessionManager.UserId,
                 MovieId = id
            };
            return View(vm);
        }

        public IActionResult Delete(int id)
        {
            if (_commentService.IsDeleted(id))
            {
                return RedirectToAction("List", "Movie");
            }
            return RedirectToAction("Account", "User");
        }
    }
}

TVDailyCriticUI/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using TVDailyCriticUI.AuthHandler;
using TVDailyCriticUI.Services;
using TVDailyCriticUI.ViewModels;

namespace TVDailyCriticUI.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;
        private readonly SessionManager _sessionManager;

        public MovieController(IMovieService movieService, IUserService userService, SessionManager sessionManager)
        {
            _movieService = movieService;
            _userService = userService;
            _sessionManager = sessionManager;
        }

        public IActionResult List(FilterMovieViewModel filter)
        {
            var model = new FilterMovieViewModel();
            var movies = new List<MovieViewModel>();
            if (filter.Movie != null)
            {
                movies = _movieService.List().Where(x => x.MovieTitle.ToLower().Contains(filter.Movie.MovieTitle.ToLower())).ToList();
            }
            else
            {
                movies = _movieService.List();
            }
            model.Movies = movies;
            return View(model);
        }

        public IActionResult Create()
        {
            return View(new MovieViewModel
            {
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert([Bind("ImageFile,CreatedDate,ReleaseDate,Description,MovieTitle,Producer,Writer,Director")] MovieViewModel movie)
        {
            if (ModelState.IsValid)
            {
                if (movie.ImageFile.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        movie.ImageFile.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        movie.Image = fileBytes;
                    }
                }
                movie.AddedBy = _sessionManager.UserId;
                _movieService.Create(movie);
            }
            return RedirectToAction("List", "Movie");
        }

        public IActionResult Details(int id)
        {
            var movie = _movieService.Get(id);
            return View(movie);
        }

        public IActionResult RatingsStatistics(int id)
        {
            MovieViewModel movieViewModel = _movieService.Get(id);
            List<UserViewModel> users = _userService.List();

            RatingsStatisticsViewModel viewModel = new RatingsStatisticsViewModel();
            List<CommentViewModel> commentsViewModel = new List<CommentViewModel>(movieViewModel.Comments);

            foreach(var item in commentsViewModel)
            {
                viewModel.MeanRating += item.Rating;
            }

            List<UserViewModel> tempUsers = new List<UserViewModel>(users);
            foreach(var user in tempUsers)
            {
                int index = commentsViewModel.FindIndex(f => f.UserId == user.UserId);
                if(!(index >= 0))
                {
                    users.Remove(user);
                }
            }

            viewModel.TotalUsers = users.Count;

            //Don't divide by zero
            if (commentsViewModel.Count != 0)
            {
                viewModel.MeanRating /= commentsViewModel.Count;
                viewModel.ModeRating = commentsViewModel.GroupBy(x => x.Rating).OrderByDescending(grp => grp.Count()).Select(grp => grp.Key).First();
                viewModel.PercentageMenRating = 100 * users.FindAll(x => x.Gender == 0).Count / commentsViewModel.Count;
                viewModel.PercentageWomenRating = 100 * users.FindAll(x => x.Gender == 1).Count / commentsViewModel.Count;
                viewModel.PercentageAdultsRating = 100 * users.FindAll(x => x.Age >= 18).Count / commentsViewModel.Count;
                viewModel.PercentageTeenagersRating = 100 * users.FindAll(x => x.Age < 18 && x.Age > 12).Count / commentsViewModel.Count;
            }

            viewModel.MovieTitle = movieViewModel.MovieTitle;

            return View(viewModel);
        }

        public IActionResult Delete(int id)
        {
            if (_movieService.IsDeleted(id))
            {
                return RedirectToAction("List", "Movie");
            }

            return RedirectToAction("Account", "User");
        }

        public IActionResult Search(FilterMovieViewModel filter)
        {
            var model = new FilterMovieViewModel();
            var movies = new List<MovieViewModel>();
            if (filter.Movie != null)
            {
                movies = _movieService.Search(filter);
            }
            else
            {
                movies = _movieService.List();
            }

            model.Movies = movies;
            return View(model);
        }

        public IActionResult Update(int id)
        {
            var movie = _movieService.Get(id);
            return View(movie);
        }

        [HttpPost]
        public IActionResult Edit([Bind("MovieId,ImageFile,CreatedDate,ReleaseDate,Description,MovieTitle")] MovieViewModel movie)
        {
            if (ModelState.IsValid)
            {
                if (movie.ImageFile.Length > 0)
                {
                    using (var ms = new MemoryStream())
                    {
                        movie.ImageFile.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        movie.Image = fileBytes;
                    }
                }
                movie.AddedBy = _sessionManager.UserId;
                _movieService.Update(movie);
            }
            return RedirectToAction("List", "Movie");
        }
    }
}

TVDailyCriticUI/Views/Movie/Create.cshtml
@model TVDailyCriticUI.ViewModels.MovieViewModel
@{
    ViewBag.Title = "Movie new";
}

<form asp-action="Insert" asp-controller="Movie" enctype="multipart/form-data" method="post">
    <div class="card mb-5">
        <div class="card-header">
            <div class="row">
                <label class="col">Movie new</label>
            </div>
        </div>
        <div class="card-body">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="ImageFile" class="control-label"></label>
                    <input asp-for="ImageFile" accept="image/*" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label class="control-label">Title</label>
                    <input asp-for="MovieTitle" class="form-control" />
                    <span asp-validation-for="MovieTitle" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label class="control-label">Director</label>
                    <input asp-for="Director" class="form-control" />
                    <span asp-validation-for="Director" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Writer</label>
                    <input asp-for="Writer" class="form-control" />
                    <span asp-validation-for="Writer" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Producer</label>
                    <input asp-for="Producer" class="form-control" />
                    <span asp-validation-for="Producer" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label class="control-label">Description</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="control-label">Release Date</label>
                    <input asp-for="ReleaseDate" class="form-control" />
                    <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                </div>
            </div>
            <hr />
            <div class="form-row mb-6">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

TVDailyCriticUI/Views/Movie/Details.cshtml
@model TVDailyCriticUI.ViewModels.MovieViewModel
@using Microsoft.AspNetCore.Http;
@{
    ViewBag.Title = "Movie details";
}

<div class="card mb-5">
    <div class="card-header">
        <div class="row">
            <label class="col">Movie details</label>
        </div>
    </div>
    <div class="card-body">
        <div class="form-row">
            <div class="form-group col-md-12">
                @{
                    string base64String = string.Empty;

                    if (Model.Image != null)
                        base64String = Convert.ToBase64String(Model.Image, 0, Model.Image.Length);
                }
                <img class="text-center p-3" src="data:image/jpeg;base64,@base64String" width="200" height="290" />
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Movie Title</label>
                @Html.EditorFor(model => model.MovieTitle, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
            <div class="form-group col-md-6">
                <label>Release Date</label>
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label>Producer</label>
                @Html.EditorFor(model => model.Producer, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
            <div class="form-group col-md-4">
                <label>Director</label>
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
            <div class="form-group col-md-4">
                <label>Writer</label>
                @Html.EditorFor(model => model.Writer, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <label>Description</label>
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
            </div>
        </div>
        <div class="form-row">

        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <a class="nav-link text-primary" asp-area="" asp-route-id="@Model.MovieId" asp-controller="Movie" asp-action="RatingsStatistics">Ratings Statistics</a>
            </div>
        </div>
        <hr />
        @if (@Context.Session.GetString("Role") == "Admin")
        {
            <a asp-action="Update" class="btn btn-info" asp-route-id="@Model.MovieId">Edit</a>
        }
    </div>
</div>
<br />
<br />
<div class="card">
    <div class="card-header">
        <div class="row">
            <label class="col">@Html.DisplayFor(model => model.Comments.Count) comments</label>
        </div>
    </div>
    <div class="row p-12">
        @foreach (var item in Model.Comments)
        {
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-11">
                                <span class="badge badge-dark" height:20px">
                                    @Html.DisplayFor(modelItem => item.User.Firstname)
                                    @Html.DisplayFor(modelItem => item.User.Lastname)
                                </span>
                                <span class="badge badge-primary badge-pill" align="right">Rated it @item.Rating</span>
                                @if (@Context.Session.GetString("Role") == "Admin")
                                {
                                    <a asp-action="Delete" class="btn btn-danger float-right" asp-controller="Comment" asp-route-id="@item.CommentId">Delete</a>
                                }
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group col-md-12">
                                @Html.DisplayFor(modelItem => item.CommentText)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    @if (@Context.Session.GetString("IsStateLogged") == "true")
    {
        <div class="row p-2">
            <div class="col-sm-12" align="right">
                <a asp-action="Create" asp-controller="Comment" asp-route-id="@Model.MovieId" class="btn btn-outline-primary">Add new comment</a>
            </div>
        </div>
    }
</div>

TVDailyCriticUI/Views/Movie/List.cshtml
@model TVDailyCriticUI.ViewModels.FilterMovieViewModel
@using Microsoft.AspNetCore.Http;
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form asp-action="List" method="get" asp-controller="Movie">
    <div class="form-row">
        <div class="form-group col-md-12">
            <input asp-for="Movie.MovieTitle" placeholder="Search..." class="form-control" />
        </div>
        <div class="form-group col-md-1" align="right">
            <input type="submit" value="Search" class="btn btn-success" />
        </div>
    </div>
</form>

@if (@Context.Session.GetString("IsStateLogged") == "true")
{
    <div class="row" style="margin-bottom:10pt">
        <div class="col-sm-12" align="right">
            <a asp-action="Create" class="btn btn-outline-primary">Create new movie</a>
        </div>
    </div>
}

<div class="list-group">
    @foreach (var item in Model.Movies)
    {
        <a class="list-group-item list-group-item-action flex-column align-items-start" asp-action="Details" asp-route-id="@item.MovieId">
            <div class="card" asp-action="Details" asp-route-id="@item.MovieId">
                @{
                    string base64String = string.Empty;

                    if (item.Image != null)
                        base64String = Convert.ToBase64String(item.Image, 0, item.Image.Length);
                }

                <div class="card-body">
                    <img class="float-left p-3" src="data:image/jpeg;base64,@base64String" width="105" height="140" />
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.MovieTitle)</h5>
                    <p class="card-text">@Html.DisplayFor(modelItem => item.Description)</p>
                </div>
            </div>
        </a>
        <div class="card-footer">
            <a asp-action="Details" class="btn btn-outline-info" asp-route-id="@item.MovieId">Details</a>

            @if (@Context.Session.GetString("Role") == "Admin")
            {
                <a asp-action="Update" class="btn btn-outline-warning" asp-route-id="@item.MovieId">Edit</a>
                <a asp-action="Delete" class="btn btn-outline-danger" asp-route-id="@item.MovieId">Delete</a>
            }
        </div>
    }
</div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

TVDailyCriticUI/Views/Movie/RatingsStatistics.cshtml
@model TVDailyCriticUI.ViewModels.RatingsStatisticsViewModel
@using TVDailyCriticUI.ViewModels;

@{

}

<h3>Ratings Statistics for @Model.MovieTitle</h3>
<table class="table table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Metric</th>
            <th scope="col">Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Total amount of users rated</td>
            <td>@Model.TotalUsers</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Rating Mode</td>
            <td>@Model.ModeRating</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>Rating Mean</td>
            <td>@Model.MeanRating</td>
        </tr>
        <tr>
            <th scope="row">4</th>
            <td>Percentage of Men rated</td>
            <td>@Model.PercentageMenRating %</td>
        </tr>
        <tr>
            <th scope="row">5</th>
            <td>Percentage of Women rated</td>
            <td>@Model.PercentageWomenRating %</td>
        </tr>
        <tr>
            <th scope="row">6</th>
            <td>Percentage of Adults Rated</td>
            <td>@Model.PercentageAdultsRating %</td>
        </tr>
        <tr>
            <th scope="row">7</th>
            <td>Percentage of Teenagers Rated</td>
            <td>@Model.PercentageTeenagersRating %</td>
        </tr>
    </tbody>
</table>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

TVDailyCriticUI/Views/Movie/Update.cshtml
@model TVDailyCriticUI.ViewModels.MovieViewModel
@{
    ViewBag.Title = "Movie edit";
}
<form asp-action="Edit" asp-controller="Movie" method="post" enctype="multipart/form-data">
    <div class="card mb-5">
        <div class="card-header">
            <div class="row">
                <label class="col">Movie edit</label>
            </div>
        </div>
        <div class="card-body">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="ImageFile" class="control-label"></label>
                    <input asp-for="ImageFile" accept="image/*" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label>Movie Title</label>
                    <input asp-for="MovieTitle" class="form-control" />
                    <span asp-validation-for="MovieTitle" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label>Producer</label>
                    <input asp-for="Producer" class="form-control" />
                    <span asp-validation-for="Producer" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label>Director</label>
                    <input asp-for="Director" class="form-control" />
                    <span asp-validation-for="Director" class="text-danger"></span>
                </div>
                <div class="form-group col-md-4">
                    <label>Writer</label>
                    <input asp-for="Writer" class="form-control" />
                    <span asp-validation-for="Writer" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label>Description</label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input asp-for="CreatedDate" class="form-control" hidden="hidden" />
                    <span asp-validation-for="CreatedDate" class="text-danger" hidden="hidden"></span>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label>Release Date</label>
                    <input asp-for="ReleaseDate" class="form-control" />
                    <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                </div>
            </div>
            <hr />
            <div class="form-row mb-6">
                <input asp-for="MovieId" class="form-control" hidden="hidden" />
                <input type="submit" value="Edit" class="btn btn-warning" />
            </div>
        </div>
    </div>
    <br />
</form>